### ISSUE TITLE
Link to kattisrc requires authentication.

### ISSUE THREAD

**Issue by mewmew** [karlek/kattis#1]
The link to `kattisrc` requires authentication and is not accessible to _open_ users of Kattis. The link https://kth.kattis.com/download/kattisrc redirects to the page https://kth.kattis.com/login?todo=redirect which displays the follow error message:

> The page you are trying to access requires you to be logged in.

**Comment by mewmew** [comment]
Changing the subdomain to open works, https://open.kattis.com/download/kattisrc

Perhaps the alternative link could also be added to the readme?

**Comment by karlek** [comment]
Figure out clean solution with #2

**Comment by karlek** [comment]
Hm, it appears to be the same config file except:

``` ini
[kattis]
loginurl: https://open.kattis.com/login
submissionurl: https://open.kattis.com/submit
```

**Comment by mewmew** [comment]
Open is now default, thus this issue is resolved.
