### ISSUE TITLE
Give open users some love <3

### ISSUE THREAD

**Issue by mewmew** [karlek/kattis#2]
The submission link `https://kth.kattis.com/submissions/%s` is hardcoded in `kattis.py`. Maybe the subdomain info could be extracted from `kattisrc` such that it works for both `open.kattis.com` and `kth.kattis.com`?

From [kattis.py:22](https://github.com/karlek/kattis/blob/master/kattis.py#L22)

``` python
command_browser = 'xdg-open "https://kth.kattis.com/submissions/%s"' % (ret)
```

**Comment by karlek** [comment]
Hmm, problem is that I lab on kth.kattis and compete for rank on open.kattis.. I'm thinking about a solution.. Might implement a context switcher setting.

**Comment by karlek** [comment]
Made a (permanent) temporary ugly fix for open users in the README :palm_tree:

**Comment by mewmew** [comment]
The (permanent) temporary fix has been in place for a while. Closing this issue to reflect the received love <3
